production:
  cloud_name: Rails.application.credentials(:CLOUDNIARY_CLOUD_NAME)
  api_key: Rails.application.credentials(:CLOUDNIARY_API_KEY)
  api_secret: Rails.application.credentials(:CLOUDNIARY_API_SECRET)
  secure: true
  cdn_subdomain: true
